name: CI
on:
  push:
    branches: [ main, staging ]
  pull_request:

permissions:
  contents: read

jobs:
  workspace:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [storefront, medusa, importer]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm -v

      - name: Install workspace
        run: pnpm -w install --frozen-lockfile

      - name: Lint (${{ matrix.app }})
        run: pnpm --filter "./apps/${{ matrix.app }}" run --if-present lint

      - name: Build (${{ matrix.app }})
        if: matrix.app != 'storefront'
        run: pnpm --filter "./apps/${{ matrix.app }}" run --if-present build

      - name: Build storefront
        if: matrix.app == 'storefront'
        run: pnpm --filter "./apps/${{ matrix.app }}" run --if-present build
        env:
          NEXT_PUBLIC_MEDUSA_URL: ${{ secrets.NEXT_PUBLIC_MEDUSA_URL }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          REVALIDATE_SECRET: ${{ secrets.REVALIDATE_SECRET }}

      - name: Run importer (smoke)
        if: matrix.app == 'importer'
        env:
          IMPORTER_CONFIG: ${{ secrets.IMPORTER_CONFIG_JSON }}
          MEDUSA_BACKEND_URL: ${{ secrets.MEDUSA_BACKEND_URL }}
          ALPHA_TOKEN: ${{ secrets.ALPHA_TOKEN }}
          BETA_KEY: ${{ secrets.BETA_KEY }}
        run: pnpm --filter "./apps/importer" start
